name: Push temp image

on:
  push:
    branches: "main"

  workflow_dispatch:

jobs:
  check_dep:
    runs-on: ubuntu-latest
    name: Check python requirements file and update
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for new package version and update
        run: |
          # Get current version
          current_version=$(grep -oP 'runpod==\K[^"]+' ./builder/requirements.txt)

          # Get new version
          new_version=$(curl -s https://pypi.org/pypi/runpod/json | jq -r .info.version)
          echo "NEW_VERSION_ENV=$new_version" >> $GITHUB_ENV

          if [ -z "$new_version" ]; then
              echo "Failed to fetch the new version."
              exit 1
          fi

          # Check if the version is already up-to-date
          if [ "$current_version" = "$new_version" ]; then
              echo "The package version is already up-to-date."
              exit 0
          fi

          # Update requirements.txt
          sed -i "s/runpod==.*/runpod==$new_version/" ./builder/requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/bake-action@v5
        with:
          push: true
          targets: ["base-1180", "base-1210", "worker-1180", "worker-1210"]
          
