name: Push temp image

on:
  push:
    branches: "main"
    tags: "latest"

  workflow_dispatch:

jobs:
  check_dep:
    runs-on: ubuntu-latest
    name: Check python requirements file and update
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for new package version and update
        run: |
          # Get current version
          current_version=$(grep -oP 'runpod==\K[^"]+' ./builder/requirements.txt)

          # Get new version
          new_version=$(curl -s https://pypi.org/pypi/runpod/json | jq -r .info.version)
          echo "NEW_VERSION_ENV=$new_version" >> $GITHUB_ENV

          if [ -z "$new_version" ]; then
              echo "Failed to fetch the new version."
              exit 1
          fi

          # Check if the version is already up-to-date
          if [ "$current_version" = "$new_version" ]; then
              echo "The package version is already up-to-date."
              exit 0
          fi

          # Update requirements.txt
          sed -i "s/runpod==.*/runpod==$new_version/" ./builder/requirements.txt

  push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: beamaia/temp_runpod_vllm
          tags: latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

